# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lewis Buckley
email: lewis@lewisbuckley.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Lewis Buckley is a professional software engineer with over 10 years experience developing web applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lewispb
github_username:  lewispb
name: Lewis Buckley

# Build settings
plugins:
  - jekyll-feed
  - jekyll-gravatar
  - jekyll-postcss
  - jekyll-purgecss

sass:
  load_paths:
    - css

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - node_modules
  - netlify.toml
  - bin
  - .gitignore
